# Aufgabenblatt 1

Patrick Zierahn (7065799)
Thorben Janssen (7047766)

## Aufgabe 1

**1. Wie kann die Anzahl der Zeilen und Spalten eines NumPy-Arrays bestimmt werden?**

An NumPy-Arrays lässt sich .shape aufrufen. Dies ist ein Tuple das die Dimension zurück liefert.

**2. Was unterscheidet die Funktionen numpy.array und numpy.zeros?**

Mit numpy.array läst sich eine Matrix erstellen.
Mit numpy.zeros((n, m)) läst sich eine n*m Matrixs erstellen die mit nullen gefühlt ist.

**3. Wie kann der Datentyp eines gegebenen NumPy-Arrays ermittelt werden?**

Die Funktion type(a) gibt Auskunft darüber um was für einen Datentyp es sich handelt.

**4. Was bedeutet .T hinter dem Variablennamen eines NumPy-Arrays? Beispielsweise: a.T**

Das T bedeutet das die Matrix transponiert wird.

**5. Was machen die Funktionen xlabel und ylabel aus matplotlib.pyplot?**

Mit matplotlib lassen sich Grafiken und Charts generieren.
xlabel und ylabel setzt die x- und y-Axsen beschriftung.


## Aufgabe 2

In [15]:
import numpy as np

# 1. Erzeugt zunächst einen Vektor u als 1D-Array mit 100 Nullen
u = np.zeros((100))
print("u =", u)

# 2. Erzeugt zudem einen Vektor v als 1D-Array aus der Liste: [0,1,2,3,4,5,6,7,8,9,10,11].
v = np.array([0,1,2,3,4,5,6,7,8,9,10,11])
print("v =", v)

# 3. Formt den Vektor v nun in eine Matrix m (2D-Array) um, die aus drei Zeilen und vier Spalten besteht.
# Tipp: NumPy kennt eine Funktion, um die Form (engl. shape) eines Arrays zu ändern.
m = v.reshape((3,4))
print("m =", m)

# 4. Multipliziert alle Einträge der Matrix m mit dem konstanten Faktor 1.2.
m = m * 1.2
print("m =", m)

# 5. Ändert nun den Datentyp der Matrix m auf np.int.
# Tipp: Nutzt die Methode astype eines NumPy-Arrays.
m = m.astype(np.int)
print("m =", m)

# 6. Multipliziert alle Einträge der Matrix m erneut mit dem konstanten Faktor 1.2.
# Von welchem Datentyp ist jetzt das Ergebnis?
m = m * 1.2
print("m =", m)
print("type(m) =", type(m))

# 7. Berechnet das Hadamard-Produkt (elementweise Multiplikation)
# der Matrix m mit sich selbst (m⊙m).
m = m * m
print("m =", m)

u = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
v = [ 0  1  2  3  4  5  6  7  8  9 10 11]
m = [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
m = [[ 0.   1.2  2.4  3.6]
 [ 4.8  6.   7.2  8.4]
 [ 9.6 10.8 12.  13.2]]
m = [[ 0  1  2  3]
 [ 4  6  7  8]
 [ 9 10 12 13]]
m = [[ 0.   1.2  2.4  3.6]
 [ 4.8  7.2  8.4  9.6]
 [10.8 12.  14.4 15.6]]
type(m) = <class 'numpy.ndarray'>
m = [[  0.     1.44   5.76  12.96]
 [ 23.04  51.84  70.56  92.16]
 [116.64 144.   207.36 243.36]]
