# Aufgabenblatt 1

Patrick Zierahn (7065799)
Thorben Janssen (7047766)

## Aufgabe 1

**1. Wie kann die Anzahl der Zeilen und Spalten eines NumPy-Arrays bestimmt werden?**

An NumPy-Arrays lässt sich .shape aufrufen. Dies ist ein Tuple das die Dimension zurück liefert.

**2. Was unterscheidet die Funktionen numpy.array und numpy.zeros?**

Mit numpy.array läst sich eine Matrix erstellen.
Mit numpy.zeros((n, m)) läst sich eine n*m Matrixs erstellen die mit nullen gefühlt ist.

**3. Wie kann der Datentyp eines gegebenen NumPy-Arrays ermittelt werden?**

Die Funktion type(a) gibt Auskunft darüber um was für einen Datentyp es sich handelt.

**4. Was bedeutet .T hinter dem Variablennamen eines NumPy-Arrays? Beispielsweise: a.T**

Das T bedeutet das die Matrix transponiert wird.

**5. Was machen die Funktionen xlabel und ylabel aus matplotlib.pyplot?**

Mit matplotlib lassen sich Grafiken und Charts generieren.
xlabel und ylabel setzt die x- und y-Axsen beschriftung.

In [7]:
import numpy as np

b = np.array([[1,2,3],[4,5,4]])
print(b)
print(b.T)
print(b.shape)

[[1 2 3]
 [4 5 4]]
[[1 4]
 [2 5]
 [3 4]]
(2, 3)
